# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_auto_20161115_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_medica',
            name='fecha_atendida',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cita_medica',
            name='observacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
