# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_auto_20161116_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_medica',
            name='fecha_atendida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita_medica',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
